// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createSupabaseFetch } from "./api-key-fetch";
import {
  getSupabasePublishableKey,
  getSupabasePublishableKeyCandidates,
  getSupabaseUrl,
  missingEnvMessage,
} from "./env.server";


export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = getSupabaseUrl();
    const SUPABASE_PUBLISHABLE_KEY = getSupabasePublishableKey();

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = missingEnvMessage(missing);
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(getSupabasePublishableKeyCandidates()),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // `getClaims` verifies locally against the project JWKS. A session minted
    // before the project's signing keys changed - which is exactly what a
    // second device with an older cached session carries - makes the underlying
    // `jose` verifier throw raw errors such as "jws protected header is
    // invalid". Never let that reach the UI: fall back to asking the Auth API
    // to verify the token, and otherwise report a plain 401 so the client can
    // refresh or sign in again.
    let claims: Record<string, unknown> | undefined;

    try {
      const { data, error } = await supabase.auth.getClaims(token);
      if (!error && data?.claims) claims = data.claims as unknown as Record<string, unknown>;
    } catch {
      claims = undefined;
    }

    if (!claims) {
      const { data: userData, error: userError } = await supabase.auth.getUser(token);
      if (userError || !userData?.user) {
        throw new Error("Unauthorized: Session expired, please sign in again");
      }
      claims = { sub: userData.user.id, email: userData.user.email };
    }

    const sub = typeof claims["sub"] === "string" ? (claims["sub"] as string) : undefined;
    if (!sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: sub,
        claims,
      },
    });
  },
);
