// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createSupabaseFetch, sanitizeApiKey } from "./api-key-fetch";


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const env = import.meta.env as unknown as Record<string, string | undefined>;
  const procEnv = typeof process !== "undefined" && process.env ? process.env : {};

  const SUPABASE_URL =
    sanitizeApiKey(env["VITE_SUPABASE_URL"]) || sanitizeApiKey(procEnv["SUPABASE_URL"]);

  // All keys this build knows about. The first one is used; if the project
  // answers "Invalid API key" (bundle built with a rotated/other key), the
  // shared fetch wrapper transparently retries with the next candidate.
  const KEY_CANDIDATES = [
    env["VITE_SUPABASE_PUBLISHABLE_KEY"],
    env["VITE_SUPABASE_ANON_KEY"],
    procEnv["SUPABASE_PUBLISHABLE_KEY"],
    procEnv["SUPABASE_ANON_KEY"],
  ]
    .map((value) => sanitizeApiKey(value))
    .filter((value): value is string => Boolean(value))
    .filter((value, index, all) => all.indexOf(value) === index);

  const SUPABASE_PUBLISHABLE_KEY = KEY_CANDIDATES[0];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message =
      `Missing Supabase environment variable(s): ${missing.join(", ")}. ` +
      `Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env before building ` +
      `(they are inlined at build time), or connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(KEY_CANDIDATES),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
